repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-toml

# Temporarily disabled hooks:
# - flake8
# - mypy
# - black
# - isort
# - pygrep-hooks
# - yesqa

ci:
  autofix_prs: false
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_branch: ""
